import {chromium,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {createApp} from '../server/app.js';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from 'vite';
const dir=mkdtempSync(join(tmpdir(),'astralab-browser-'));const app=createApp({dbPath:join(dir,'db.sqlite'),dataDir:join(dir,'private'),env:{APP_ORIGIN:'http://localhost:3100',API_RATE_LIMIT:'3000'}});const vite=await createServer({server:{middlewareMode:true,hmr:{port:24679}},appType:'spa'});app.use(vite.middlewares);const server=app.listen(3100,'127.0.0.1');const browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const base='http://localhost:3100';const results=[];
try{
 for(const width of (process.env.BROWSER_QUICK?[375]:[1920,1440,1280,1024,768,480,375])){
  await page.setViewportSize({width,height:950});
  for(const path of ['/','/free','/paid','/authors','/register','/login','/about','/categories']){
   await page.goto(base+path,{waitUntil:'networkidle'});
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`Overflow at ${width} ${path}`);
   assert.equal(await page.locator('img').evaluateAll(images=>images.every(i=>i.complete&&i.naturalWidth>0)),true,`Broken image ${width} ${path}`);
  }
  results.push({width,publicRoutes:8,overflow:false,brokenImages:false});
 }
 await page.setViewportSize({width:1440,height:1000});await page.goto(base);await page.getByRole('button',{name:'Open global search'}).click();await page.getByRole('textbox',{name:'Search products, authors and categories'}).fill('LivingCritz');await page.getByRole('button',{name:/LivingCritz\.js/}).waitFor();await page.getByRole('button',{name:/LivingCritz\.js/}).click();assert.ok(page.url().includes('/authors/LivingCritz'));
 await page.setViewportSize({width:375,height:850});await page.goto(base);await page.getByRole('button',{name:'Open navigation'}).click();await page.getByRole('navigation',{name:'Mobile navigation'}).getByRole('link',{name:'Free Stuff'}).click();assert.ok(page.url().endsWith('/free'));await page.getByRole('navigation',{name:'Mobile navigation'}).waitFor({state:'hidden'});
 await page.goto(base+'/register');await page.getByRole('textbox',{name:'Username',exact:true}).fill('browser_member');await page.getByRole('textbox',{name:'Email address'}).fill('browser@example.com');await page.locator('input[name="password"]').fill('BrowserSecurePassword123');await page.locator('input[name="confirmPassword"]').fill('BrowserSecurePassword123');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Create Account',exact:true}).click();await page.getByRole('heading',{name:'Welcome, browser_member.'}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 for(const path of ['/dashboard','/dashboard/downloads','/dashboard/purchases','/dashboard/wishlist','/dashboard/profile','/dashboard/settings']){await page.goto(base+path,{waitUntil:'networkidle'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('h1').count(),1);}
 await page.goto(base+'/admin');await page.getByRole('heading',{name:'Access Denied',exact:true}).waitFor();await page.goto(base+'/dropper');await page.getByRole('heading',{name:'Access Denied',exact:true}).waitFor();
 const db=app.locals.db;const user=db.prepare("SELECT * FROM users WHERE username='browser_member'").get();
 db.prepare("UPDATE users SET role='FREE_DROPPER' WHERE id=?").run(user.id);
 await page.goto(base+'/dropper/products/create',{waitUntil:'networkidle'});assert.equal(await page.getByRole('button',{name:'PAID',exact:true}).count(),0);assert.equal(await page.getByText('Price: $0.00').count(),1);
 await page.getByRole('textbox',{name:'Product name'}).fill('Browser resource fixture');await page.getByRole('textbox',{name:'Description',exact:true}).fill('An isolated resource fixture used to verify the full creator workflow.');await page.getByLabel('Category',{exact:true}).selectOption('plugins');await page.getByLabel('Product file',{exact:true}).setInputFiles({name:'fixture.json',mimeType:'application/json',buffer:Buffer.from('{"fixture":true}')});await page.getByRole('button',{name:'Submit for review'}).click();await page.getByRole('heading',{name:'My Products',exact:true}).waitFor();await page.getByRole('cell',{name:'Browser resource fixture',exact:true}).waitFor();const product=db.prepare('SELECT * FROM products WHERE authorId=?').get(user.id);assert.equal(product.type,'FREE');assert.equal(product.status,'PENDING_REVIEW');
 db.prepare("UPDATE users SET role='PAID_DROPPER' WHERE id=?").run(user.id);await page.goto(base+'/dropper/products/create',{waitUntil:'networkidle'});await page.getByRole('button',{name:/PAID Offer a premium creation/}).click();assert.equal(await page.getByRole('spinbutton',{name:'Price (USD)'}).count(),1);
 db.prepare("UPDATE users SET role='ADMIN' WHERE id=?").run(user.id);await page.setViewportSize({width:1440,height:1000});for(const path of ['/admin','/admin/users','/admin/droppers','/admin/products','/admin/categories','/admin/orders','/admin/payments','/admin/downloads','/admin/reviews','/admin/reports','/admin/settings','/admin/logs']){await page.goto(base+path,{waitUntil:'networkidle'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`Overflow ${path}`);assert.equal(await page.locator('h1').count(),1,`Page heading ${path}`);}
 await page.goto(base+'/admin/products',{waitUntil:'networkidle'});await page.getByRole('button',{name:'Approve',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Confirm',exact:true}).click();await page.getByLabel('Status for Browser resource fixture').waitFor();await expect(page.getByLabel('Status for Browser resource fixture')).toHaveValue('PUBLISHED');await page.goto(base+'/products/'+product.id,{waitUntil:'networkidle'});await page.getByRole('heading',{name:product.title}).waitFor();for(const tab of ['Description','Features','Installation','Changelog','Screenshots','Reviews']){await page.getByRole('tab',{name:new RegExp('^'+tab)}).click();assert.equal(await page.getByRole('tabpanel').count(),1);}
 for(const width of (process.env.BROWSER_QUICK?[375]:[1920,1440,1280,1024,768,480,375])){await page.setViewportSize({width,height:950});for(const path of ['/dashboard','/dropper','/dropper/products/create','/admin','/admin/users','/admin/settings','/products/'+product.id]){await page.goto(base+path,{waitUntil:'networkidle'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`Protected overflow ${width} ${path}`);}}
 await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/');await page.screenshot({path:'home-desktop.png',fullPage:true});await page.setViewportSize({width:375,height:850});await page.goto(base+'/');await page.screenshot({path:'home-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);console.log(JSON.stringify({responsive:results,accountRegistration:true,search:true,mobileMenu:true,dashboards:true,roleBasedEditor:true,adminRoutes:12,moderation:true,productTabs:true,pageErrors:errors},null,2));
}finally{await browser.close();await vite.close();await new Promise(r=>server.close(r));app.locals.db.close();rmSync(dir,{recursive:true,force:true});}
