import { useEffect,useState } from 'react';
import { Link,useSearchParams,useParams } from 'react-router-dom';
import { useApi,date,roleLabel } from '../api';
import { CategoryCard,ProductFilters,ProductGrid,AuthorCard } from '../components/Marketplace';
import { Icon,PageHeading,LoadingSkeleton,ErrorState,ErrorPage,Badge } from '../components/UI';
export function Catalog({type='FREE'}){const [params,setParams]=useSearchParams();const [filters,setFilters]=useState(Object.fromEntries(params));const [debounced,setDebounced]=useState(filters);useEffect(()=>{const t=setTimeout(()=>{setDebounced(filters);setParams(Object.fromEntries(Object.entries(filters).filter(([,v])=>v)),{replace:true});},250);return()=>clearTimeout(t);},[filters]);const categories=useApi('/categories');const products=useApi('/products?'+new URLSearchParams({...debounced,type}));const paid=type==='PAID';return <main className="container catalog-page"><div className="breadcrumb"><Link to="/">AstraLab</Link><Icon name="ChevronRight" size={14}/><span>{paid?'Paid Stuff':'Free Stuff'}</span></div><PageHeading eyebrow={paid?'PREMIUM CREATIONS':'COMMUNITY RESOURCES'} title={paid?'Paid Stuff':'Free Stuff'} description={paid?'Premium resources built to take your projects further.':'High-quality resources. Zero cost.'} action={<div className={'catalog-emblem '+(paid?'purple':'blue')}><Icon name={paid?'Gem':'Download'} size={35}/></div>}/><div className="catalog-tabs"><Link className={!paid?'active':''} to="/free"><Icon name="Download" size={17}/> Free Stuff</Link><Link className={paid?'active':''} to="/paid"><Icon name="Gem" size={17}/> Paid Stuff</Link></div><ProductFilters categories={categories.data||[]} filters={filters} setFilters={setFilters} paid={paid}/><div className="results-meta"><span>{products.loading?'Loading resources…':`${products.data?.length||0} resources`}</span>{Object.values(filters).some(v=>v)&&<button className="text-link" onClick={()=>setFilters({})}>Reset filters <Icon name="X" size={13}/></button>}</div>{products.loading?<LoadingSkeleton count={6}/>:products.error?<ErrorState error={products.error} retry={products.refresh}/>:<ProductGrid products={products.data} showDownload={!paid} showBuy={paid}/>}<div className="catalog-note"><Icon name="ShieldCheck" size={17}/> Every published resource goes through creator submission and platform review.</div></main>;}
export function Categories(){const {data,loading,error}=useApi('/categories');return <main className="container catalog-page"><PageHeading eyebrow="EXPLORE THE POSSIBILITIES" title="Find your building blocks." description="From your first plugin to your next world. Choose a category to explore."/>{loading?<LoadingSkeleton/>:error?<ErrorState error={error}/>:<div className="all-category-grid">{data.map(c=><Link className="full-category-card" key={c.id} to={'/free?category='+c.id}><div className="category-icon"><Icon name={c.icon} size={25}/></div><h2>{c.name}</h2><p>{c.description}</p><span className="text-link">Explore resources <Icon name="ArrowUpRight" size={16}/></span></Link>)}</div>}</main>;}
export function Authors(){const {data,loading,error}=useApi('/authors');return <main className="container catalog-page"><PageHeading eyebrow="THE PEOPLE BEHIND ASTRALAB" title="Built by creators." description="Meet the developers and creators behind AstraLab."/>{loading?<LoadingSkeleton/>:error?<ErrorState error={error}/>:<div className="author-grid">{data.map(a=><AuthorCard key={a.username} author={a}/>)}</div>}</main>;}
export function AuthorProfile(){const {username}=useParams();const {data,loading,error}=useApi('/authors/'+encodeURIComponent(username));if(loading)return <main className="container catalog-page"><LoadingSkeleton/></main>;if(error)return error.status===404?<ErrorPage/>:<ErrorState error={error}/>;return <main className="container catalog-page"><div className="breadcrumb"><Link to="/authors">Authors</Link><Icon name="ChevronRight" size={14}/><span>{data.username}</span></div><div className="author-profile"><img src={data.avatar||'/assets/astralab-logo.jpg'} alt={data.username+"'s avatar"}/><div><span className="eyebrow">ASTRALAB CREATOR</span><h1>{data.username}</h1><Badge variant="creator"><Icon name="BadgeCheck" size={14}/>{roleLabel(data.role)}</Badge>{data.bio&&<p>{data.bio}</p>}<div className="profile-meta"><span>{data.products.length} published products</span><span>{data.downloads} downloads</span>{data.createdAt&&<span>Joined {date(data.createdAt)}</span>}</div></div></div><div className="section-heading"><div><h2>Creations by {data.username}</h2><p>Resources published on AstraLab.</p></div></div><ProductGrid products={data.products}/></main>;}
