import { useState } from 'react';
import { Link,useLocation } from 'react-router-dom';
import { useApi,api,date,money,roleLabel } from '../api';
import { useApp } from '../context';
import { EmptyState,Icon,PageHeading,LoadingSkeleton,ErrorState,DataTable,Badge } from '../components/UI';
import { ProductGrid } from '../components/Marketplace';
import { PasswordField } from './Auth';
export function Stats({items}){return <div className="stats-grid">{items.map(([label,value,icon])=><div className="stat-card" key={label}><div><span>{label}</span><Icon name={icon} size={18}/></div><strong>{value}</strong></div>)}</div>;}
export default function UserDashboard(){const {user}=useApp();const {data,loading,error,refresh}=useApi('/account');const location=useLocation();const page=location.pathname.split('/')[2]||'overview';if(loading)return <LoadingSkeleton type="dashboard"/>;if(error)return <ErrorState error={error} retry={refresh}/>;
 if(page==='settings'||page==='profile')return <ProfileSettings profile={page==='profile'}/>;
 if(page==='downloads')return <><PageHeading eyebrow="YOUR RESOURCE LIBRARY" title="My Downloads" description="Pick up where your last build left off."/><DataTable empty="No downloads yet." rows={data.downloads} columns={[{key:'title',label:'Resource'},{key:'createdAt',label:'Downloaded',render:r=>date(r.createdAt)}]} onAction={r=><Link className="small-button" to={'/products/'+r.productId}>View resource <Icon name="ArrowUpRight" size={13}/></Link>}/></>;
 if(page==='purchases')return <><PageHeading eyebrow="PREMIUM RESOURCES" title="My Purchases" description="Your purchases and payment status, in one place."/><DataTable empty="No purchases yet." rows={data.purchases} columns={[{key:'title',label:'Resource'},{key:'amount',label:'Amount',render:r=>money(r.amount)},{key:'status',label:'Status',render:r=><Badge variant={r.status==='PAID'?'free':''}>{r.status}</Badge>},{key:'createdAt',label:'Date',render:r=>date(r.createdAt)}]} onAction={r=><Link className="small-button" to={'/products/'+r.productId}>View Product</Link>}/></>;
 if(page==='wishlist')return <><PageHeading eyebrow="SAVED FOR YOUR NEXT BUILD" title="Wishlist" description="Keep the resources that caught your eye close by."/>{data.wishlist.length?<ProductGrid products={data.wishlist} saved onRemove={refresh}/>:<EmptyState title="Your wishlist has room to grow." description="Save a resource with its bookmark button to find it here." icon="Bookmark" action={<Link className="button secondary" to="/free">Explore resources <Icon name="ArrowRight" size={15}/></Link>}/>}</>;
 return <><PageHeading eyebrow="YOUR SPACE ON ASTRALAB" title={'Welcome, '+user.username+'.'} description="A new day. A new world to build." action={<Link className="button secondary" to="/free">Explore resources<Icon name="ArrowUpRight" size={16}/></Link>}/><Stats items={[["Downloads",data.totals.downloads,'Download'],['Paid purchases',data.totals.purchases,'ShoppingBag'],['Saved products',data.wishlist.length,'Bookmark']]}/><div className="dashboard-panels"><section className="dashboard-panel"><h2>Recent downloads</h2>{data.downloads.length?<div className="recent-list">{data.downloads.slice(0,4).map(d=><Link key={d.id} to={'/products/'+d.productId}><Icon name="Package"/><div><strong>{d.title}</strong><span>{date(d.createdAt)}</span></div><Icon name="ArrowUpRight" size={17}/></Link>)}</div>:<EmptyState icon="Download" title="No downloads yet." description="Your resources will appear here." compact/>}<Link className="text-link" to="/dashboard/downloads">My Downloads<Icon name="ArrowRight" size={14}/></Link></section><section className="dashboard-panel"><h2>Recent purchases</h2>{data.purchases.length?<div className="recent-list">{data.purchases.slice(0,4).map(d=><Link key={d.id} to={'/products/'+d.productId}><Icon name="ShoppingBag"/><div><strong>{d.title}</strong><span>{money(d.amount)} · {d.status}</span></div><Icon name="ArrowUpRight" size={17}/></Link>)}</div>:<EmptyState icon="ShoppingBag" title="No purchases yet." description="Your next upgrade is ahead." compact/>}<Link className="text-link" to="/dashboard/purchases">My Purchases<Icon name="ArrowRight" size={14}/></Link></section></div><section className="dashboard-panel account-panel"><div><h2>Account information</h2><p>{user.email}</p></div><Badge>{roleLabel(user.role)}</Badge><Link className="text-link" to="/dashboard/profile">Edit profile<Icon name="ArrowUpRight" size={14}/></Link></section><section className="dashboard-panel"><div className="section-heading"><div><h2>Saved products</h2><p>A shortlist for your next project.</p></div><Link className="text-link" to="/dashboard/wishlist">View wishlist<Icon name="ArrowRight" size={14}/></Link></div>{data.wishlist.length?<ProductGrid products={data.wishlist.slice(0,3)} saved/>:<EmptyState compact icon="Bookmark" title="Nothing saved yet." description="Bookmark resources to find them here."/>}</section></>;
}
export function ProfileSettings({profile=false}){const {user,setUser,toast}=useApp();const [form,setForm]=useState({username:user.username,bio:user.bio||'',currentPassword:'',newPassword:''});const [busy,setBusy]=useState(false);const [error,setError]=useState('');const change=e=>setForm({...form,[e.target.name]:e.target.value});const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const body=profile?{username:form.username,bio:form.bio}:{currentPassword:form.currentPassword,newPassword:form.newPassword};const result=await api('/account',{method:'PATCH',body});setUser(result.user);toast(profile?'Your profile has been updated.':'Your password has been updated.');setForm({...form,currentPassword:'',newPassword:''});}catch(e){setError(e.message);}finally{setBusy(false);}};return <><PageHeading eyebrow="ACCOUNT PREFERENCES" title={profile?'Your Profile':'Settings'} description={profile?'How you appear in the AstraLab community.':'Keep your account secure and up to date.'}/><form className="dashboard-panel settings-form" onSubmit={submit}>{error&&<p className="form-error">{error}</p>}{profile?<><div className="profile-edit-avatar"><span className="initial-avatar">{user.username[0].toUpperCase()}</span><div><strong>{user.username}</strong><span>{roleLabel(user.role)}</span></div></div><label className="form-label">Username<input name="username" value={form.username} onChange={change} minLength={3} maxLength={40} required/></label><label className="form-label">Bio <span className="optional">optional</span><textarea name="bio" value={form.bio} onChange={change} maxLength={1000} placeholder="Tell the community about your work."/></label><label className="form-label">Email<input value={user.email} disabled/></label><div className="profile-info"><span>Joined {date(user.createdAt)}</span><Badge>{roleLabel(user.role)}</Badge></div></>:<><h2>Change password</h2><PasswordField name="currentPassword" label="Current password" value={form.currentPassword} onChange={change} minLength={1}/><PasswordField name="newPassword" label="New password" value={form.newPassword} onChange={change} autoComplete="new-password"/><p className="field-hint">At least 12 characters. Other sessions will be signed out.</p></>}<button className="button primary" disabled={busy}>{busy?'Saving…':'Save changes'}<Icon name="Check" size={16}/></button></form></>;}
