import { useState } from 'react';
import { Link,useLocation } from 'react-router-dom';
import { api,useApi,date,money } from '../api';
import { useApp } from '../context';
import { PageHeading,LoadingSkeleton,ErrorState,EmptyState,Badge,Icon,DataTable,ConfirmModal,Chart } from '../components/UI';
import { Stats } from './Dashboard';
export default function DropperDashboard(){const {user,toast}=useApp();const {data,loading,error,refresh}=useApi('/dropper');const page=useLocation().pathname.split('/')[2]||'overview';const [remove,setRemove]=useState(null);const paid=user.role==='PAID_DROPPER'||user.role==='ADMIN';if(loading)return <LoadingSkeleton type="dashboard"/>;if(error)return <ErrorState error={error}/>;const downloads=data.products.reduce((n,p)=>n+p.downloads,0);const chart=Object.values(data.downloads.reduce((rows,d)=>{const day=d.createdAt.slice(0,10);rows[day]||={date:day,count:0};rows[day].count++;return rows;},{}));const create=<Link className="button primary" to="/dropper/products/create"><Icon name="Plus" size={17}/>{paid?'Create Product':'Create Free Product'}</Link>;
 const deleteModal=remove&&<ConfirmModal danger title="Delete this product?" description={'“'+remove.title+'” will be deleted. Products with recorded purchases or downloads must be hidden instead.'} onCancel={()=>setRemove(null)} onConfirm={async()=>{try{await api('/products/'+remove.id,{method:'DELETE'});toast('Product deleted.');refresh();}catch(e){toast(e.message,'error');}setRemove(null);}}/>;
 if(page==='products')return <><PageHeading eyebrow="CREATOR STUDIO" title="My Products" description="Your creations, submissions and review feedback." action={create}/><DataTable rows={data.products} empty="Your first creation starts here." columns={[{key:'title',label:'Resource',render:p=><div><strong>{p.title}</strong>{p.rejectionReason&&<small className="rejection-text">{p.rejectionReason}</small>}</div>},{key:'type',label:'Type',render:p=><Badge variant={p.type==='FREE'?'free':'paid'}>{p.type==='FREE'?'FREE':money(p.price)}</Badge>},{key:'status',label:'Status',render:p=><Badge>{p.status.replaceAll('_',' ')}</Badge>},{key:'downloads',label:'Downloads'}]} onAction={p=><><Link className="small-button" to={'/products/'+p.id}>View</Link><Link className="small-button" to={'/dropper/products/'+p.id+'/edit'}>Edit</Link><button className="small-button danger-text" onClick={()=>setRemove(p)}>Delete</button></>}/>{deleteModal}</>;
 if(page==='sales'||page==='revenue')return <><PageHeading eyebrow="PREMIUM CREATOR" title={page==='sales'?'Sales':'Revenue'} description="Only your orders and verified payments are shown here."/><Stats items={[["Completed sales",data.sales?.filter(s=>s.status==='PAID').length||0,'ShoppingBag'],['Revenue',money(data.revenue),'Wallet']]}/><DataTable rows={data.sales} empty="No sales yet." columns={[{key:'title',label:'Resource'},{key:'amount',label:'Amount',render:r=>money(r.amount)},{key:'status',label:'Payment status',render:r=><Badge>{r.status}</Badge>},{key:'createdAt',label:'Date',render:r=>date(r.createdAt)}]}/></>;
 if(page==='downloads')return <><PageHeading eyebrow="CREATOR STUDIO" title="Downloads" description="Recorded downloads of your published resources."/><DataTable rows={data.downloads} empty="No downloads yet." columns={[{key:'title',label:'Resource'},{key:'createdAt',label:'Date',render:r=>date(r.createdAt)}]}/></>;
 return <><PageHeading eyebrow={paid?'FREE + PAID CREATOR':'FREE RESOURCE CREATOR'} title={page==='analytics'?'Your Analytics':'Your Creator Studio'} description={paid?'Build free and premium resources for the Minecraft community.':'Share free resources with the Minecraft community.'} action={create}/><Stats items={[["Products",data.products.length,'Package'],['Published',data.products.filter(p=>p.status==='PUBLISHED').length,'CheckCircle2'],['Downloads',downloads,'Download'],...(paid?[['Revenue',money(data.revenue),'Wallet']]:[])]}/><section className="dashboard-panel"><h2>Download activity</h2><p>Recorded activity across your resources.</p><Chart data={chart}/></section><section className="dashboard-panel"><h2>Submissions</h2>{data.products.length?<DataTable rows={data.products.slice(0,5)} columns={[{key:'title',label:'Resource'},{key:'status',label:'Status',render:p=><Badge>{p.status.replaceAll('_',' ')}</Badge>},{key:'updatedAt',label:'Updated',render:r=>date(r.updatedAt)}]} onAction={p=><Link className="small-button" to={'/dropper/products/'+p.id+'/edit'}>Edit</Link>}/>:<EmptyState compact title="Ready when you are." description="Create a resource and submit it for platform review." action={create}/>}</section><div className="permission-note"><Icon name="ShieldCheck" size={20}/><div><strong>{paid?'You can publish free and paid resources.':'Your resources are always free.'}</strong><p>All submissions go through platform review. You can manage your own resources.</p></div></div>{deleteModal}</>;
}
