import { Link } from 'react-router-dom';
import { useApi } from '../api';
import { CategoryCard,AuthorCard,ProductGrid } from '../components/Marketplace';
import { Icon,Logo,LoadingSkeleton,ErrorState,EmptyState } from '../components/UI';
function SectionTitle({eyebrow,title,description,link,to}){return <div className="section-heading"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2><p>{description}</p></div>{link&&<Link className="text-link" to={to}>{link}<Icon name="ArrowUpRight" size={16}/></Link>}</div>;}
export default function Home(){const categories=useApi('/categories');const featured=useApi('/products?featured=true');const authors=useApi('/authors');const free=useApi('/products?type=FREE');const paid=useApi('/products?type=PAID');return <main>
 <section className="hero"><div className="hero-orbit orbit-one" aria-hidden="true"/><div className="hero-orbit orbit-two" aria-hidden="true"/><div className="hero-corner hero-corner-left" aria-hidden="true"><span className="crosshair">+</span><span>CRAFTED FOR<br/>YOUR NEXT WORLD</span></div><div className="hero-corner hero-corner-right" aria-hidden="true"><span>AN OPEN UNIVERSE<br/>OF POSSIBILITIES</span><span className="crosshair">+</span></div><div className="hero-content"><div className="hero-brand"><Logo/></div><div className="hero-badge"><span className="status-dot"/>THE MINECRAFT CREATOR MARKETPLACE</div><h1>Build. Create.<br/><span>Upgrade.</span></h1><p>Discover premium Minecraft resources, tools and creations<br className="desktop-break"/> made by developers for developers.</p><div className="hero-buttons"><Link className="button primary" to="/free"><Icon name="Compass" size={19}/>Explore Free Stuff<Icon name="ArrowRight" size={17}/></Link><Link className="button secondary" to="/paid">Browse Paid Stuff<Icon name="ArrowUpRight" size={17}/></Link></div><div className="hero-support"><span>Free resources</span><i/><span>Premium creations</span><i/><span>Trusted creators</span></div></div><div className="hero-bottom"><span><Icon name="Box" size={14}/> BUILT FOR MINECRAFT. BUILT FOR YOU.</span><a href="#explore" aria-label="Scroll to marketplace"><span>SCROLL TO EXPLORE</span><Icon name="ArrowDown" size={15}/></a></div></section>
 <section className="section category-section container" id="explore"><SectionTitle eyebrow="YOUR NEXT PROJECT STARTS HERE" title="Explore AstraLab" description="Everything you need to build better Minecraft projects." link="All categories" to="/categories"/>{categories.loading?<LoadingSkeleton count={8} type="categories"/>:categories.error?<ErrorState error={categories.error} retry={categories.refresh}/>:<div className="category-grid">{categories.data?.slice(0,8).map(c=><CategoryCard key={c.id} category={c}/>)}</div>}</section>
 <section className="section featured-section container"><SectionTitle eyebrow="CURATED FOR THE COMMUNITY" title="Featured on AstraLab" description="Discover resources worth checking out." link="Explore marketplace" to="/free"/>{featured.loading?<LoadingSkeleton/>:featured.data?.length?<ProductGrid products={featured.data.slice(0,3)}/>:<div className="featured-empty"><div className="featured-visual" aria-hidden="true"><div className="visual-grid"/><div className="orbit-ring"/><div className="resource-cube"><Icon name="Box" size={51}/></div><span className="visual-spark spark-1">+</span><span className="visual-spark spark-2">+</span></div><div className="featured-empty-copy"><span className="eyebrow">A SPACE FOR SOMETHING GREAT</span><h3>Your next upgrade<br/>is on the horizon.</h3><p>The marketplace is getting ready for its first creations.<br/>Meet the people building what comes next.</p><Link className="text-link" to="/authors">Meet our creators <Icon name="ArrowRight" size={16}/></Link></div><span className="featured-corner-label">NO PUBLISHED RESOURCES YET</span></div>}</section>
 <section className="section container marketplace-duo"><div className="marketplace-panel"><div className="marketplace-panel-heading"><span className="collection-symbol blue"><Icon name="Download" size={24}/></span><BadgeLabel text="FREE RESOURCES"/></div><h2>Free Stuff</h2><p>High-quality resources. Zero cost.</p>{free.data?.length?<ProductGrid products={free.data.slice(0,2)} showDownload/>:<div className="collection-empty"><Icon name="PackageOpen" size={22}/><span>No free resources published yet.</span></div>}<Link className="button secondary" to="/free">View All Free Stuff<Icon name="ArrowUpRight" size={17}/></Link></div><div className="marketplace-panel"><div className="marketplace-panel-heading"><span className="collection-symbol purple"><Icon name="Gem" size={24}/></span><BadgeLabel text="PREMIUM CREATIONS"/></div><h2>Paid Stuff</h2><p>Premium resources built to take your projects further.</p>{paid.data?.length?<ProductGrid products={paid.data.slice(0,2)} showBuy/>:<div className="collection-empty"><Icon name="PackageOpen" size={22}/><span>No premium resources published yet.</span></div>}<Link className="button secondary" to="/paid">View All Paid Stuff<Icon name="ArrowUpRight" size={17}/></Link></div></section>
 <section className="section authors-section container"><SectionTitle eyebrow="THE PEOPLE BEHIND THE PIXELS" title="Built by creators." description="Meet the developers and creators behind AstraLab." link="All authors" to="/authors"/>{authors.loading?<LoadingSkeleton/>:authors.error?<ErrorState error={authors.error}/>:<div className="author-grid">{authors.data?.slice(0,3).map(a=><AuthorCard key={a.username} author={a}/>)}</div>}</section>
 <section className="join-strip container"><div><span className="eyebrow">BUILD SOMETHING THAT MATTERS</span><h2>A new world starts with an idea.</h2><p>Find your next resource. Make your next project yours.</p></div><Link className="button primary" to="/register">Join AstraLab<Icon name="ArrowUpRight" size={17}/></Link></section>
 </main>;}
function BadgeLabel({text}){return <span className="eyebrow">{text}</span>;}
