import { useState } from 'react';
import { Link,useNavigate } from 'react-router-dom';
import { api,money } from '../api';
import { useApp } from '../context';
import { Badge,EmptyState,Icon } from './UI';
export function CategoryCard({category}){return <Link className="category-card" to={'/free?category='+category.id}><div className="category-icon"><Icon name={category.icon} size={23}/></div><span>{category.name==='Server Configs'?'Configs':category.name}</span><Icon className="category-arrow" name="ArrowUpRight" size={14}/></Link>;}
export function AuthorCard({author}){return <article className="author-card"><div className="author-card-top"><span className="eyebrow">ASTRALAB CREATOR</span><Icon name="ArrowUpRight" size={17}/></div><img className="author-portrait" src={author.avatar||'/assets/astralab-logo.jpg'} alt={author.username+"'s avatar"} loading="lazy"/><h3>{author.username}</h3><Badge variant="creator"><Icon name="BadgeCheck" size={13}/>Creator</Badge><div className="author-card-bottom"><span>{author.products||0} published products</span><Link to={'/authors/'+encodeURIComponent(author.username)}>View Profile <Icon name="ArrowRight" size={14}/></Link></div></article>;}
export function ProductCard({product,showDownload=false,showBuy=false,saved=false,onRemove}){const {user,toast}=useApp();const navigate=useNavigate();const [isSaved,setIsSaved]=useState(saved);const [busy,setBusy]=useState(false);
 const save=async()=>{if(!user){navigate('/login');return;}setBusy(true);try{await api('/wishlist/'+product.id,{method:isSaved?'DELETE':'POST'});setIsSaved(!isSaved);toast(isSaved?'Removed from your wishlist.':'Saved to your wishlist.');if(isSaved)onRemove?.();}catch(e){toast(e.message,'error');}finally{setBusy(false);}};
 return <article className="product-card"><Link className="product-thumbnail" to={'/products/'+product.id}>{product.thumbnail?<img src={product.thumbnail} alt={product.title} loading="lazy"/>:<div className="product-fallback"><Icon name={product.category?.icon||'Box'} size={50}/><span>{product.category?.name}</span></div>}<Badge variant={product.type==='FREE'?'free':'paid'}>{product.type==='FREE'?'FREE':money(product.price)}</Badge></Link><button className={'save-button '+(isSaved?'saved':'')} aria-label={isSaved?'Remove from wishlist':'Save to wishlist'} disabled={busy} onClick={save}><Icon name="Bookmark" size={17}/></button><div className="product-card-body"><span className="product-category">{product.category?.name}</span><Link to={'/products/'+product.id}><h3>{product.title}</h3></Link><p>{product.description}</p><Link className="product-author" to={'/authors/'+encodeURIComponent(product.author.username)}><img className="avatar" src={product.author.avatar||'/assets/astralab-logo.jpg'} alt=""/>{product.author.username}</Link><div className="product-metrics"><span><Icon name="Star" size={14}/>{product.rating?product.rating.toFixed(1):'No reviews'}</span><span><Icon name={product.type==='FREE'?'Download':'ShoppingBag'} size={14}/>{product.type==='FREE'?product.downloads:product.sales} {product.type==='FREE'?'downloads':'sales'}</span></div><div className="product-card-actions"><Link className="button secondary" to={'/products/'+product.id}>View Product <Icon name="ArrowUpRight" size={15}/></Link>{showDownload&&<Link className="button primary" to={'/products/'+product.id}>Download</Link>}{showBuy&&<Link className="button primary" to={'/products/'+product.id}>Buy Now</Link>}</div></div></article>;
}
export function ProductGrid({products=[],...props}){return products.length?<div className="product-grid">{products.map(p=><ProductCard key={p.id} product={p} {...props}/>)}</div>:<EmptyState title="Good things are on the horizon." description="No resources have been published here yet. Explore the categories or meet the creators behind AstraLab." icon="PackageOpen" action={<Link className="text-link" to="/authors">Meet the creators <Icon name="ArrowRight" size={15}/></Link>}/>;}
export function ProductFilters({filters,setFilters,categories=[],paid=false}){const change=(key,value)=>setFilters({...filters,[key]:value});return <div className="product-filters"><label className="search-field"><Icon name="Search" size={18}/><input aria-label="Search resources" placeholder="Search resources…" value={filters.q||''} onChange={e=>change('q',e.target.value)}/></label><div className="filter-selects"><label><Icon name="SlidersHorizontal" size={16}/><select aria-label="Filter by category" value={filters.category||''} onChange={e=>change('category',e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><select aria-label="Filter by Minecraft version" value={filters.version||''} onChange={e=>change('version',e.target.value)}><option value="">Minecraft version</option>{['1.21.5','1.21.4','1.21','1.20.6','1.20.4','1.20','1.19','1.18','1.16.5','1.12.2','1.8.9'].map(v=><option key={v}>{v}</option>)}</select></label>{paid&&<label><select aria-label="Filter by price" value={filters.maxPrice||''} onChange={e=>change('maxPrice',e.target.value)}><option value="">Any price</option><option value="10">Under $10</option><option value="25">Under $25</option><option value="50">Under $50</option></select></label>}{paid&&<label><select aria-label="Minimum rating" value={filters.rating||''} onChange={e=>change('rating',e.target.value)}><option value="">Any rating</option><option value="4">4+ stars</option><option value="3">3+ stars</option></select></label>}<label><select aria-label="Sort resources" value={filters.sort||'latest'} onChange={e=>change('sort',e.target.value)}><option value="latest">Latest</option><option value="downloads">Most Downloaded</option><option value="popular">Most Popular</option>{paid&&<><option value="price">Price: low to high</option><option value="rating">Top Rated</option></>}</select></label></div></div>;}
