import { useEffect,useRef,useState } from 'react';
import { Link,NavLink,useLocation,useNavigate } from 'react-router-dom';
import { useApp } from '../context';
import { api,useApi } from '../api';
import { Icon,Logo } from './UI';
const links=[['Home','/'],['Free Stuff','/free'],['Paid Stuff','/paid'],['Authors','/authors'],['About','/about']];
export function SearchModal({onClose}) {
 const ref=useRef();const [query,setQuery]=useState('');const [results,setResults]=useState({products:[],authors:[],categories:[]});const [loading,setLoading]=useState(false);const [error,setError]=useState('');const navigate=useNavigate();
 useEffect(()=>{ref.current?.showModal();},[]);
 useEffect(()=>{let live=true;if(!query.trim()){setResults({products:[],authors:[],categories:[]});setLoading(false);return;}setLoading(true);const t=setTimeout(()=>Promise.all([api('/products?q='+encodeURIComponent(query)),api('/authors?q='+encodeURIComponent(query)),api('/categories')]).then(([products,authors,categories])=>{if(live){setResults({products,authors,categories:categories.filter(c=>c.name.toLowerCase().includes(query.toLowerCase()))});setLoading(false);setError('');}}).catch(e=>{if(live){setError(e.message);setLoading(false);}}),250);return()=>{live=false;clearTimeout(t);};},[query]);
 const go=path=>{onClose();navigate(path);};
 return <dialog ref={ref} className="search-modal" onCancel={e=>{e.preventDefault();onClose();}}><div className="search-modal-input"><Icon name="Search"/><input autoFocus aria-label="Search products, authors and categories" placeholder="Search the AstraLab universe…" value={query} onChange={e=>setQuery(e.target.value)}/><button className="search-esc" aria-label="Close search" onClick={onClose}>Esc</button></div><div className="search-results">{!query?<><span className="eyebrow">START EXPLORING</span><button onClick={()=>go('/free')}><Icon name="Download"/>Free resources<Icon name="ArrowUpRight"/></button><button onClick={()=>go('/paid')}><Icon name="Gem"/>Premium creations<Icon name="ArrowUpRight"/></button><button onClick={()=>go('/authors')}><Icon name="Users"/>Our creators<Icon name="ArrowUpRight"/></button></>:loading?<p>Searching…</p>:error?<p className="form-error">{error}</p>:<>{results.products.map(p=><button key={p.id} onClick={()=>go('/products/'+p.id)}><Icon name="Box"/>{p.title}<small>{p.type==='FREE'?'FREE':'Paid'}</small></button>)}{results.authors.map(a=><button key={a.username} onClick={()=>go('/authors/'+encodeURIComponent(a.username))}><img className="avatar" src={a.avatar||'/assets/astralab-logo.jpg'} alt=""/>{a.username}<small>Creator</small></button>)}{results.categories.map(c=><button key={c.id} onClick={()=>go('/free?category='+c.id)}><Icon name={c.icon}/>{c.name}<small>Category</small></button>)}{!Object.values(results).some(r=>r.length)&&<p>No results for “{query}”. Try a category or creator name.</p>}</>}</div><div className="search-footer"><Icon name="Search" size={13}/> Products, authors & categories</div></dialog>;
}
export function NotificationMenu(){const {data,refresh}=useApi('/notifications');const [open,setOpen]=useState(false);const unread=data?.filter(n=>!n.read).length||0;return <div className="notification-wrap"><button className="icon-button" aria-label={`Notifications${unread?', '+unread+' unread':''}`} aria-expanded={open} onClick={()=>setOpen(!open)}><Icon name="Bell" size={19}/>{unread>0&&<span className="notification-count">{unread}</span>}</button>{open&&<div className="notification-menu"><div className="notification-header"><strong>Notifications</strong><button className="text-link" onClick={async()=>{await api('/notifications/read',{method:'PATCH'});refresh();}}>Mark all read</button></div>{!data?.length?<p>No notifications.</p>:data.map(n=><div key={n.id} className={!n.read?'unread':''}><strong>{n.title}</strong><p>{n.message}</p></div>)}</div>}</div>;}
export default function Navbar(){const {user,logout}=useApp();const [menu,setMenu]=useState(false);const [search,setSearch]=useState(false);const location=useLocation();const navigate=useNavigate();const menuRef=useRef(null);
 useEffect(()=>{setMenu(false);setSearch(false);},[location.pathname]);
 useEffect(()=>{document.body.style.overflow=menu?'hidden':'';const main=document.getElementById('main-content');const footer=document.querySelector('footer');if(main)main.inert=menu;if(footer)footer.inert=menu;const toggle=document.querySelector('.mobile-toggle');if(menu)menuRef.current?.querySelector('a')?.focus();const trap=e=>{if(!menu||e.key!=='Tab')return;const focusable=[toggle,...menuRef.current.querySelectorAll('a,button')].filter(Boolean);const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}};document.addEventListener('keydown',trap);return()=>{document.body.style.overflow='';if(main)main.inert=false;if(footer)footer.inert=false;document.removeEventListener('keydown',trap);};},[menu]);
 useEffect(()=>{const handler=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSearch(s=>!s);}if(e.key==='Escape')setMenu(false);};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
 return <><header className="navbar"><div className="nav-inner"><Link to="/" className="brand" aria-label="AstraLab home"><Logo/><span>AstraLab<span className="brand-dot">.</span></span></Link><nav className="desktop-nav" aria-label="Main navigation">{links.map(([text,path])=><NavLink end={path==='/'} key={path} to={path}>{text}</NavLink>)}</nav><div className="nav-actions"><button className="nav-search" aria-label="Open global search" onClick={()=>setSearch(true)}><Icon name="Search" size={18}/><kbd>⌘ K</kbd></button><span className="nav-divider"/>{user?<><NotificationMenu/><Link className="nav-login" to="/dashboard">Dashboard</Link><button className="nav-logout" onClick={async()=>{await logout();navigate('/');}}>Logout</button><Link className="user-avatar" to="/dashboard/profile" aria-label="Your profile">{user.avatar?<img src={user.avatar} alt=""/>:user.username.slice(0,1).toUpperCase()}</Link></>:<><Link className="nav-login" to="/login">Login</Link><Link className="button register-button" to="/register">Register <Icon name="ArrowUpRight" size={15}/></Link></>}<button className="mobile-toggle icon-button" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}><Icon name={menu?'X':'Menu'}/></button></div></div></header>{menu&&<nav className="mobile-menu" aria-label="Mobile navigation" ref={menuRef} tabIndex={-1}>{links.map(([text,path],i)=><NavLink key={path} to={path}><small>0{i+1}</small>{text}<Icon name="ArrowUpRight"/></NavLink>)}<div className="mobile-menu-auth">{user?<><Link className="button primary" to="/dashboard">My Dashboard</Link><button className="button secondary" onClick={async()=>{await logout();setMenu(false);}}>Logout</button></>:<><Link className="button secondary" to="/login">Login</Link><Link className="button primary" to="/register">Create Account</Link></>}</div><p>Build. Create. Upgrade.</p></nav>}{search&&<SearchModal onClose={()=>setSearch(false)}/>}</>;}
