import { useEffect,useRef } from 'react';
import { Link } from 'react-router-dom';
import { useApp } from '../context';
import { ArrowDown,ArrowLeft,ArrowRight,ArrowUpRight,BadgeCheck,Bell,Bookmark,Box,Braces,ChartNoAxesCombined,Check,CheckCircle2,ChevronRight,Circle,CircleAlert,CircleCheck,Clock,Code2,Compass,CreditCard,Database,Download,Eye,EyeOff,File,FileArchive,Flag,Gamepad2,Gem,Gift,Github,Image,Images,Layers,LayoutDashboard,LockKeyhole,LogOut,Map,Menu,MessageCircle,MessageSquare,Orbit,Package,PackageCheck,PackageOpen,PanelsTopLeft,Plus,Puzzle,Rocket,RotateCw,ScrollText,Search,Settings,ShieldCheck,ShoppingBag,SlidersHorizontal,Sparkles,Star,TriangleAlert,UserRound,Users,Wallet,Wrench,X } from 'lucide-react';
const Icons={ArrowDown,ArrowLeft,ArrowRight,ArrowUpRight,BadgeCheck,Bell,Bookmark,Box,Braces,ChartNoAxesCombined,Check,CheckCircle2,ChevronRight,Circle,CircleAlert,CircleCheck,Clock,Code2,Compass,CreditCard,Database,Download,Eye,EyeOff,File,FileArchive,Flag,Gamepad2,Gem,Gift,Github,Image,Images,Layers,LayoutDashboard,LockKeyhole,LogOut,Map,Menu,MessageCircle,MessageSquare,Orbit,Package,PackageCheck,PackageOpen,PanelsTopLeft,Plus,Puzzle,Rocket,RotateCw,ScrollText,Search,Settings,ShieldCheck,ShoppingBag,SlidersHorizontal,Sparkles,Star,TriangleAlert,UserRound,Users,Wallet,Wrench,X};
export function Icon({name='Orbit',size=20,...props}){const I=Icons[name]||Icons.Orbit;return <I size={size} strokeWidth={1.6} aria-hidden="true" {...props}/>;}
export function Logo({className=''}){const {config}=useApp();return <img className={'brand-logo '+className} src={config?.logo||'/assets/astralab-logo.jpg'} alt="AstraLab" width="80" height="80"/>;}
export function Badge({children,variant='',className=''}){return <span className={`badge ${variant} ${className}`}>{children}</span>;}
export function EmptyState({icon='Orbit',title='No products yet.',description='New resources will appear here when creators publish them.',action,compact=false}){return <div className={'empty-state '+(compact?'compact':'')}><div className="empty-orbit"><Icon name={icon} size={28}/></div><h3>{title}</h3><p>{description}</p>{action}</div>;}
export function LoadingSkeleton({count=3,type='cards'}){return <div className={'skeleton-grid '+type} aria-busy="true" aria-label="Loading content">{Array.from({length:count},(_,i)=><div className="skeleton" key={i}><div/><span/><span/></div>)}</div>;}
export function ErrorState({error,retry}){return <div className="error-panel" role="alert"><Icon name="CircleAlert"/><div><h3>{error?.status===403?'Access Denied':'Unable to load this content'}</h3><p>{error?.message||'Please try again.'}</p>{retry&&<button className="text-link" onClick={retry}>Try again <Icon name="RotateCw" size={14}/></button>}</div></div>;}
export function ConfirmModal({title='Confirm this action?',description,children,onConfirm,onCancel,danger=false,confirmLabel='Confirm',busy=false}) {
 const ref=useRef(null);useEffect(()=>{const previous=document.activeElement;ref.current?.showModal();return()=>previous?.focus();},[]);
 return <dialog ref={ref} className="confirm-modal" onCancel={e=>{e.preventDefault();onCancel();}}><div className="modal-top"><div className="modal-symbol"><Icon name={danger?'TriangleAlert':'ShieldCheck'} size={26}/></div><button className="icon-button" aria-label="Close dialog" onClick={onCancel}><Icon name="X"/></button></div><h2>{title}</h2>{description&&<p>{description}</p>}{children}<div className="modal-actions"><button className="button secondary" onClick={onCancel} disabled={busy}>Cancel</button><button className={'button '+(danger?'danger':'primary')} onClick={onConfirm} disabled={busy}>{busy?'Working…':confirmLabel}</button></div></dialog>;
}
export function PageHeading({eyebrow,title,description,action}){return <div className="page-heading"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>;}
export function ErrorPage({code=404}){const info={404:['Lost in space?','The page you’re looking for has moved or doesn’t exist.'],403:['Access Denied','Your account does not have permission to access this page.'],500:['A disturbance in the signal.','We couldn’t complete this request. Please try again shortly.']}[code];return <main className="error-page"><div className="error-code">{code}</div><Icon name="Orbit" size={54}/><h1>{info[0]}</h1><p>{info[1]}</p><Link className="button primary" to="/">Back to AstraLab <Icon name="ArrowRight" size={17}/></Link></main>;}
export function DataTable({columns,rows,empty='No records yet.',onAction}){if(!rows?.length)return <EmptyState icon="Database" title={empty} description="Records will appear here as your marketplace grows."/>;return <div className="table-scroll"><table><thead><tr>{columns.map(c=><th key={c.key}>{c.label}</th>)}{onAction&&<th>Actions</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{columns.map(c=><td key={c.key}>{c.render?c.render(r):r[c.key]??'—'}</td>)}{onAction&&<td><div className="table-actions">{onAction(r)}</div></td>}</tr>)}</tbody></table></div>;}
export function Chart({data=[]}){if(!data.length)return <EmptyState icon="ChartNoAxesCombined" title="Your first data point is ahead." description="This chart uses recorded downloads. There’s no activity yet." compact/>;const max=Math.max(...data.map(d=>d.count),1);return <div className="chart" role="img" aria-label="Recorded downloads by date">{data.slice().reverse().map(d=><div key={d.date} className="chart-column"><span>{d.count}</span><div style={{height:Math.max(4,(d.count/max)*150)}}/><small>{d.date.slice(5)}</small></div>)}</div>;}
